In [4]:
import os
from pandas import DataFrame
from datetime import datetime, timedelta
with os.scandir('D:\monthlyreports') as files:
    critical_view=[]
    file_date=[]
    for file in files:
        substring=file.name[-14:-4]
        dated_substring=datetime.strptime(substring, '%Y-%m-%d')
        dated_substring=dated_substring.date()
        file_date.append(dated_substring)
        #print(dated_substring)
        current_date=datetime.today()
        current_date=current_date.date()
        #print(current_date)
        difference_in_dates=current_date - dated_substring
        difference_in_days=difference_in_dates.days
        #print(difference_in_days)
        
        #diff_days=timedelta(days=1) 
        if (difference_in_days==1):
            #datetime.timedelta(days=1)):
            print("Accept")
            critical_view.append("Acceptable")
        else:
            #print(difference_in_days)
            #print("Unacceptable")
            critical_view.append("Unacceptable")
    #critical_view.append("Unacceptable")
    #critical=DataFrame(critical_view)
    #FileDates=DataFrame(file_date)
    timeliness_reports={'File Date':file_date,'Critical View':critical_view}
    df=DataFrame(timeliness_reports, columns=['File Date','Critical View'])
        #returns with only date excluding the time keeping the type as datetime
        
        
        #getting todays date and excluding the time keeping only the date
       
        #
        #print(type(current_date))

        #print(substring)
        #print(type(dated_substring))
        
        
        
            #required_date=current_date + diff_days"""

Accept

In [5]:
df

     File Date Critical View
0   2021-03-01  Unacceptable
1   2021-03-02  Unacceptable
2   2021-03-03  Unacceptable
3   2021-03-04  Unacceptable
4   2021-03-05  Unacceptable
5   2021-03-06  Unacceptable
6   2021-03-07  Unacceptable
7   2021-03-08  Unacceptable
8   2021-03-09  Unacceptable
9   2021-03-10  Unacceptable
10  2021-03-11  Unacceptable
11  2021-03-12  Unacceptable
12  2021-03-13  Unacceptable
13  2021-03-14  Unacceptable
14  2021-03-15  Unacceptable
15  2021-03-16  Unacceptable
16  2021-03-17  Unacceptable
17  2021-03-18  Unacceptable
18  2021-03-19  Unacceptable
19  2021-03-20  Unacceptable
20  2021-03-21  Unacceptable
21  2021-03-22  Unacceptable
22  2021-03-23  Unacceptable
23  2021-03-24  Unacceptable
24  2021-03-25  Unacceptable
25  2021-03-26  Unacceptable
26  2021-03-27  Unacceptable
27  2021-03-28  Unacceptable
28  2021-03-29  Unacceptable
29  2021-03-30  Unacceptable
30  2021-05-16    Acceptable

In [49]:
#critical
FileDates

             0
0   2021-03-01
1   2021-03-02
2   2021-03-03
3   2021-03-04
4   2021-03-05
5   2021-03-06
6   2021-03-07
7   2021-03-08
8   2021-03-09
9   2021-03-10
10  2021-03-11
11  2021-03-12
12  2021-03-13
13  2021-03-14
14  2021-03-15
15  2021-03-16
16  2021-03-17
17  2021-03-18
18  2021-03-19
19  2021-03-20
20  2021-03-21
21  2021-03-22
22  2021-03-23
23  2021-03-24
24  2021-03-25
25  2021-03-26
26  2021-03-27
27  2021-03-28
28  2021-03-29
29  2021-03-30
30  2021-05-14